# tunnel_module.py (updated for wireframe and shaded support)
import os
import math
import cv2
import numpy as np
import random
import textwrap
import subprocess
import shutil
import json
import moderngl

PALETTE_RGB = {
    'orange': (1.0, 0.4, 0.2),
    'cyan': (0.0, 1.0, 1.0),
    'lime': (0.7, 1.0, 0.0),
    'pink': (1.0, 0.4, 0.7),
    'white': (1.0, 1.0, 1.0),
    'red': (1.0, 0.1, 0.1),
    'blue': (0.2, 0.2, 1.0),
    'yellow': (1.0, 1.0, 0.0),
    'teal': (0.0, 0.7, 0.6),
    'peach': (1.0, 0.8, 0.6),
}


def normalize_renderer_backend(params):
    """Normalize renderer backend setting to a supported canonical value."""

    backend = str(params.get('renderer_backend', 'software')).strip().lower()
    if backend not in {'software', 'moderngl'}:
        backend = 'software'
    params['renderer_backend'] = backend
    return backend

# Extra padding so the closest tunnel segment never intersects the near clipping
# plane. Without this offset, the recycle loop mode causes the front face to be
# exactly at z=0 which leads to white bars and z-fighting flicker. Using a
# slightly larger offset also stabilizes the geometry so the front-most segment
# does not jitter when it approaches the camera.
FRONT_OFFSET = 0.35
# Recycle a segment only after it is completely behind the camera.
# Waiting ensures the segment stays visible until its back end passes
# the viewer which avoids white flashes when recycling.

def generate_filename(params):
    """Create a descriptive file name from tunnel parameters.

    The previous implementation only used the resolution, which caused files
    generated by :mod:`batch_exporter` to overwrite each other.  The new naming
    scheme includes the tunnel dimensions, segment length, duration and speed so
    that each parameter combination results in a unique filename.
    """

    mode = 'bw' if params['color_mode'] == 'bw' else 'col'
    brightness = {
        'alternating': 'alt',
        'random': 'rnd',
        'monotonous': 'mono'
    }[params['segment_brightness']]
    markers = params['depth_markers']

    recycle = 'recy' if params.get('recycle_loop') else 'norecy'

    return (
        f"tunnel_{params['tunnel_width']:.1f}w_"
        f"{params['tunnel_height']:.1f}h_"
        f"{params['segment_length']:.1f}l_"
        f"{params['tunnel_depth']:.0f}d_"
        f"{params['duration']:.1f}s_"
        f"{params['speed']:.1f}spd_"
        f"{recycle}_"
        f"{mode}_{brightness}_{markers}.mp4"
    )


def export_video(params, output_dir=None):
    """Render a video with the exact pipeline used by the GUI export button.

    This ensures the same renderer initialization, background color, palette
    mapping, oversampling, and ffmpeg encoding are applied consistently across
    the GUI, :mod:`batch_exporter`, and :mod:`interactive_protocol` helpers.
    """

    working = dict(params)
    normalize_renderer_backend(working)
    validate_params(working)

    # GUI-only flags default to safe values so batch/CLI users get the same pipeline.
    working.setdefault('show_camera_marker', False)
    working.setdefault('motion_blur', False)
    working.setdefault('blur_samples', 5)

    renderer = create_renderer(working)
    filename = generate_filename(working)
    output_dir = output_dir or os.getcwd()
    os.makedirs(output_dir, exist_ok=True)
    final_path = os.path.join(output_dir, filename)

    width, height = compute_render_resolution(working)
    fps = float(working['fps'])
    total_frames = max(1, int(round(working['duration'] * fps)))

    oversample = max(1, int(working.get('temporal_oversample', 1)))
    blur_samples = int(working.get('blur_samples', 5)) if working.get('motion_blur') else 1
    combined_samples = max(1, oversample * max(1, blur_samples))
    frame_interval = 1.0 / fps

    ffmpeg_path = shutil.which("ffmpeg") or "C:\\ffmpeg\\bin\\ffmpeg.exe"
    if not os.path.exists(ffmpeg_path):
        raise FileNotFoundError("FFmpeg not found. Please install it or add it to your PATH.")

    ffmpeg_cmd = [
        ffmpeg_path,
        "-y",
        "-f", "rawvideo",
        "-pix_fmt", "bgr24",
        "-s", f"{width}x{height}",
        "-r", str(fps),
        "-i", "-",
        "-f", "lavfi", "-t", str(working['duration']),
        "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
        "-shortest",
        "-c:v", "libx264",
        "-preset", "slow",
        "-crf", "8",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        "-profile:v", "high",
        "-level", "4.2",
        "-c:a", "aac",
        "-b:a", "128k",
        final_path,
    ]

    process = subprocess.Popen(ffmpeg_cmd, stdin=subprocess.PIPE)

    try:
        for frame_index in range(total_frames):
            base_time = frame_index * frame_interval

            if combined_samples == 1:
                cam_z = working['speed'] * (base_time + 0.5 * frame_interval)
                frame = renderer.render_frame(cam_z)
            else:
                sub_dt = frame_interval / combined_samples
                blended = None
                for sample_idx in range(combined_samples):
                    sample_time = base_time + (sample_idx + 0.5) * sub_dt
                    cam_z = working['speed'] * sample_time
                    sub_frame = renderer.render_frame(cam_z).astype(np.float32)
                    blended = sub_frame if blended is None else blended + sub_frame
                frame = np.clip(blended / combined_samples, 0, 255).astype(np.uint8)

            if working.get('show_camera_marker'):
                center = (frame.shape[1] // 2, frame.shape[0] // 2)
                cv2.line(frame, (center[0] - 10, center[1]), (center[0] + 10, center[1]), (0, 0, 255), 2)
                cv2.line(frame, (center[0], center[1] - 10), (center[0], center[1] + 10), (0, 0, 255), 2)

            process.stdin.write(frame.tobytes())
    finally:
        process.stdin.close()
        process.wait()
        renderer.release()

    if process.returncode != 0:
        raise RuntimeError("FFmpeg failed to encode the video. Please check the console for details.")

    settings_path = final_path.replace('.mp4', '_settings.json')
    with open(settings_path, 'w', encoding='utf-8') as f:
        json.dump(working, f, indent=2)

    return final_path, settings_path

def apply_palette_color(params):
    """Synchronize ``color_rgb`` with the selected ``color_palette``.

    This mirrors the GUI dropdown mapping so previews, exports, and batch runs
    always use the exact same palette-derived RGB tuple without requiring
    callers to remember to update ``color_rgb`` manually.
    """

    palette = params.get('color_palette')
    if palette in PALETTE_RGB:
        params['color_rgb'] = PALETTE_RGB[palette]


def default_params():
    params = {
        'resolution': (1920, 1080),
        'tunnel_width': 2.0,
        'tunnel_height': 2.0,
        'segment_length': 10.0,
        'depth_markers': 'shaded',  # 'none', 'wireframe', 'shaded', 'both' 
        'duration': 5.0,
        'speed': 5.0,
        'color_mode': 'bw',
        'segment_brightness': 'alternating',  # 'alternating', 'random', 'monotonous'
        'shaded': True,  # Enable shading for depth perception
        'fade_to_back': True,
        'fade_to_back_start': 1.0,
        'fade_to_back_end': 150.0,
        'fps': 60,
        'fovy': 5.0,
        'tunnel_depth': 1000.0,
        'back_plane_color': 0.8,
        'auto_back_plane_color': True,
        'color_palette': 'orange',
        'brightness_contrast': 0.2,
        'recycle_loop': True,
        'square': True,
        'render_scale': 2.0,  # render at higher resolution and downsample for smoother videos
        'renderer_backend': 'software',
        'temporal_oversample': 1,
    }

    apply_palette_color(params)
    return params


def compute_render_resolution(params):
    """Return the actual render resolution based on the square flag."""
    width, height = params['resolution']
    if params.get('square'):
        side = min(width, height)
        return side, side
    return width, height

def apply_contrast(value, contrast):
    adjusted = 0.5 + (value - 0.5) * contrast
    return max(0.0, min(1.0, adjusted))

def generate_brightness(index, mode, contrast, seed=None):
    """Generate a brightness value for a segment index."""

    if mode == 'alternating':
        val = 1.0 if index % 2 == 0 else 0.2
    elif mode == 'random':
        # Deterministic pseudo random so that recycling does not introduce
        # temporal flicker which the human visual system interprets as a
        # velocity change.  Using ``seed`` keeps the sequence stable across
        # repeated exports while still looking random.
        rng_seed = int((seed or 0) * 1315423911 + index)
        rng = random.Random(rng_seed)
        val = rng.uniform(0.2, 1.0)
    else:
        val = 1.0

    return apply_contrast(val, contrast)

def _box_warning(message):
    """Print a warning surrounded by a unicode box for high visibility."""

    lines = [line.strip() for line in textwrap.wrap(str(message), width=76)] or [str(message)]
    width = max(len(line) for line in lines)
    horizontal = "┌" + "─" * (width + 2) + "┐"
    bottom = "└" + "─" * (width + 2) + "┘"
    print(horizontal)
    for line in lines:
        padding = " " * (width - len(line))
        print(f"│ {line}{padding} │")
    print(bottom)


def _adjust_params(params):
    """Auto-compensate incompatible parameter combinations and collect warnings."""

    adjustments = []

    def record(message):
        adjustments.append(message)

    def clamp_positive(key, minimum, message):
        value = float(params.get(key, minimum))
        if value <= 0:
            params[key] = minimum
            record(message.format(minimum))

    clamp_positive('segment_length', 0.1, 'Segment length must be positive; defaulting to {0:.2f}.')
    clamp_positive('duration', 0.1, 'Duration must be positive; defaulting to {0:.2f}s.')
    clamp_positive('tunnel_depth', params['segment_length'],
                   'Tunnel depth must be positive; defaulting to {0:.2f}.')

    speed = float(params.get('speed', 0.0))
    if speed < 0:
        params['speed'] = 0.0
        record('Speed cannot be negative; clamping to 0.0.')

    if params['segment_length'] > params['tunnel_depth']:
        params['tunnel_depth'] = params['segment_length']
        record('Tunnel depth increased to match the segment length of '
               f"{params['segment_length']:.2f}.")

    if not params.get('recycle_loop', True):
        travel = params['speed'] * params['duration']
        max_travel = params['tunnel_depth']
        if max_travel <= 0:
            params['tunnel_depth'] = params['segment_length']
            max_travel = params['tunnel_depth']
            record('Tunnel depth adjusted to allow at least one segment when recycle loop is disabled.')
        if params['duration'] > 0 and travel > max_travel:
            max_speed = max_travel / params['duration']
            params['speed'] = max_speed
            record('Depth too short for the selected speed/duration; '
                   f"reducing speed to {max_speed:.3f}.")

    render_scale = float(params.get('render_scale', 1.0))
    if render_scale <= 0:
        params['render_scale'] = 1.0
        record('Render scale must be positive; resetting to 1.0.')

    oversample = int(params.get('temporal_oversample', 1))
    if oversample <= 0:
        params['temporal_oversample'] = 1
        record('Temporal oversample must be positive; resetting to 1.')

    return adjustments


def validate_params(params):
    """Basic sanity checks for tunnel parameters."""

    normalize_renderer_backend(params)
    apply_palette_color(params)

    for message in _adjust_params(params):
        _box_warning(message)

    if params['segment_length'] <= 0:
        raise ValueError('segment_length must be positive')

    if params['tunnel_depth'] <= 0:
        raise ValueError('tunnel_depth must be positive')
    if params['segment_length'] > params['tunnel_depth']:
        raise ValueError('segment_length cannot exceed tunnel_depth')
    if params['duration'] <= 0:
        raise ValueError('duration must be positive')

    if params['speed'] < 0:
        raise ValueError('speed must be non-negative')

    fade_start = float(params.get('fade_to_back_start', 10.0))
    fade_end = float(params.get('fade_to_back_end', 400.0))
    if fade_start < 0 or fade_end < 0:
        raise ValueError('fade distances must be non-negative')
    if fade_start >= fade_end:
        raise ValueError('fade_to_back_start must be smaller than fade_to_back_end')

    render_scale = params.get('render_scale', 1.0)
    if render_scale <= 0:
        raise ValueError('render_scale must be positive')
    oversample = int(params.get('temporal_oversample', 1))
    if oversample <= 0:
        raise ValueError('temporal_oversample must be positive')
    if (not params.get('recycle_loop') and
            params['speed'] * params['duration'] > params['tunnel_depth']):
        raise ValueError('camera travels beyond tunnel depth; enable recycle_loop or adjust speed/duration/depth')


class SegmentLayout:
    """Maintain deterministic tunnel segment placement and brightness."""

    def __init__(self, params):
        self.update(params)

    def update(self, params):
        self.params = params
        self.seg_length = params['segment_length']
        self.random_seed = params.get('random_seed', 8675309)
        self.brightness_cache = {}
        self._configure_segments()

    def _configure_segments(self):
        recycle = self.params.get('recycle_loop')
        base_depth = float(self.params['tunnel_depth'])
        camera_travel = max(0.0, self.params['speed'] * self.params['duration'])

        if recycle:
            visible_margin = self.seg_length * 5
            coverage_depth = max(base_depth, self.seg_length)
            extra_segments = 4
        else:
            visible_margin = self.seg_length * 1.5
            coverage_depth = max(base_depth, camera_travel, self.seg_length)
            extra_segments = 1

        self.visible_margin = visible_margin
        self.back_plane_depth = base_depth if recycle else coverage_depth
        self.nominal_depth = coverage_depth
        self.max_visible_distance = coverage_depth + visible_margin

        self.segment_count = int(math.ceil(coverage_depth / self.seg_length)) + extra_segments
        self.segment_span = self.segment_count * self.seg_length
        self.segments = []
        for i in range(self.segment_count):
            z = -i * self.seg_length - FRONT_OFFSET
            brightness = self.get_brightness(i)
            self.segments.append({
                'z': z,
                'index': i,
                'base_index': i,
                'brightness': brightness,
            })

        self.brightness_list = [seg['brightness'] for seg in self.segments]

        if self.params.get('auto_back_plane_color'):
            avg = float(np.mean(self.brightness_list))
            self.params['back_plane_color'] = avg
            hex_val = '#{0:02X}{0:02X}{0:02X}'.format(int(avg * 255))
            print(f"Auto back plane color set to {hex_val}")

    def get_brightness(self, index):
        if index not in self.brightness_cache:
            self.brightness_cache[index] = generate_brightness(
                index,
                self.params['segment_brightness'],
                self.params['brightness_contrast'],
                self.random_seed,
            )
        return self.brightness_cache[index]

    def visible_segments(self, cam_z):
        seg_length = self.seg_length
        tunnel_span = self.segment_span
        max_visible = self.max_visible_distance
        segments_to_draw = []

        for seg in self.segments:
            base_index = seg.setdefault('base_index', seg['index'])
            rel_z = seg['z'] + cam_z

            if self.params.get('recycle_loop'):
                recycle_after = seg_length + FRONT_OFFSET
                while rel_z > recycle_after:
                    seg['z'] -= tunnel_span
                    wraps = ((seg['index'] - base_index) // self.segment_count) + 1
                    seg['index'] = base_index + wraps * self.segment_count
                    seg['base_index'] = base_index
                    seg['brightness'] = self.get_brightness(seg['index'])
                    rel_z = seg['z'] + cam_z
            else:
                if rel_z > seg_length:
                    continue

            if rel_z > seg_length + FRONT_OFFSET:
                continue
            if rel_z < -max_visible:
                continue

            brightness = seg.get('brightness')
            if brightness is None:
                brightness = self.get_brightness(seg['index'])
                seg['brightness'] = brightness
            segments_to_draw.append((rel_z, brightness))

        segments_to_draw.sort(key=lambda item: item[0])
        return segments_to_draw

class TunnelRenderer:
    @staticmethod
    def compute_resolution(params):
        return compute_render_resolution(params)

    def __init__(self, params):
        validate_params(params)
        self.params = params
        self.width, self.height = self.compute_resolution(params)
        self.render_scale = params.get('render_scale', 1.0)
        self.rwidth = int(self.width * self.render_scale)
        self.rheight = int(self.height * self.render_scale)
        self.depth_mode = params['depth_markers']
        self.ctx = moderngl.create_standalone_context()
        self.ctx.line_width = 1.0
        self.ctx.enable(moderngl.BLEND)
        self.ctx.blend_func = (moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA)
        self.ctx.enable(moderngl.DEPTH_TEST)
        self.ctx.depth_func = '<='
        # Framebuffer and frame array reused for each frame to reduce allocations
        self.color_rb = self.ctx.renderbuffer((self.rwidth, self.rheight))
        self.depth_rb = self.ctx.depth_renderbuffer((self.rwidth, self.rheight))
        self.fbo = self.ctx.framebuffer(
            color_attachments=[self.color_rb],
            depth_attachment=self.depth_rb,
        )
        self.frame = np.empty((self.rheight, self.rwidth, 3), dtype=np.uint8)

        self.vertex_shader_src = """#version 330
        in vec3 in_position;
        in float in_face_kind;
        flat out int face_kind;
        uniform mat4 model;
        uniform mat4 projection;
        void main() {
            face_kind = int(in_face_kind);
            gl_Position = projection * model * vec4(in_position, 1.0);
        }
        """

        self.fragment_shader_src = """#version 330
        flat in int face_kind;
        out vec4 fragColor;

        uniform float brightness;
        uniform bool shaded;
        uniform bool fade_back;
        uniform float fade_start;
        uniform float fade_end;
        uniform bool color_mode;
        uniform vec3 base_color;
        uniform float seg_z;
        uniform float tunnel_depth;

        void main() {
            float face_shade = 1.0;
            float depth_factor = clamp(1.0 - min(1.0, abs(seg_z) / max(tunnel_depth, 1e-6)), 0.0, 1.0);

            if (shaded) {
                if (face_kind == 0) {
                    face_shade = 0.8;
                } else if (face_kind == 1) {
                    face_shade = 1.05;
                } else {
                    face_shade = 0.9;
                }
                face_shade = clamp(0.55 + depth_factor * face_shade * 0.45, 0.3, 1.2);
            }

            float fade_factor = 1.0;
            if (fade_back) {
                float fade = smoothstep(fade_start, fade_end, -seg_z);
                fade_factor = clamp(1.0 - fade, 0.0, 1.0);
            }

            float final_brightness = brightness * fade_factor;
            vec3 base = color_mode ? base_color : vec3(1.0);
            fragColor = vec4(base * final_brightness * face_shade, 1.0);
        }
        """

        self.back_fragment_shader_src = """#version 330
        in vec3 v_pos;
        out vec4 fragColor;
        uniform float brightness;
        uniform bool color_mode;
        uniform vec3 base_color;
        void main() {
            vec3 base = color_mode ? base_color : vec3(1.0);
            fragColor = vec4(base * brightness, 1.0);
        }
        """

        self.back_vertex_shader_src = """#version 330
        in vec3 in_position;
        out vec3 v_pos;
        uniform mat4 model;
        uniform mat4 projection;
        void main() {
            v_pos = in_position;
            gl_Position = projection * model * vec4(in_position, 1.0);
        }
        """

        self.prog = self.ctx.program(
            vertex_shader=self.vertex_shader_src,
            fragment_shader=self.fragment_shader_src,
        )

        self.mvp = self.prog['model']
        self.projection = self.prog['projection']
        self.brightness = self.prog['brightness']
        self.seg_z = self.prog['seg_z']
        self.shaded = self.prog['shaded']
        self.fade_back = self.prog['fade_back']
        self.fade_start = self.prog['fade_start']
        self.fade_end = self.prog['fade_end']
        self.color_mode = self.prog['color_mode']
        self.base_color = self.prog['base_color']
        self.tunnel_depth = self.prog['tunnel_depth']

        self.back_prog = self.ctx.program(
            vertex_shader=self.back_vertex_shader_src,
            fragment_shader=self.back_fragment_shader_src,
        )
        self.back_model = self.back_prog['model']
        self.back_proj = self.back_prog['projection']
        self.back_brightness = self.back_prog['brightness']
        self.back_color_mode = self.back_prog['color_mode']
        self.back_base_color = self.back_prog['base_color']

        self.layout = SegmentLayout(self.params)
        self.init_geometry()

    def init_geometry(self):
        w, h, l = self.params['tunnel_width'], self.params['tunnel_height'], self.params['segment_length']
        vertices = np.array([
            [-w/2, -h/2, 0], [ w/2, -h/2, 0], [ w/2,  h/2, 0], [-w/2,  h/2, 0],
            [-w/2, -h/2, -l], [ w/2, -h/2, -l], [ w/2,  h/2, -l], [-w/2,  h/2, -l],
        ], dtype='f4')
        faces = [
            ([0, 3, 7, 4], 2),  # left (side)
            ([1, 2, 6, 5], 2),  # right (side)
            ([3, 2, 6, 7], 0),  # top
            ([0, 1, 5, 4], 1),  # bottom
        ]
        tris, edges = [], []

        for face, face_kind in faces:
            def pack(vertex):
                return [vertex[0], vertex[1], vertex[2], float(face_kind)]

            tris.extend([
                pack(vertices[face[0]]), pack(vertices[face[1]]), pack(vertices[face[2]]),
                pack(vertices[face[2]]), pack(vertices[face[3]]), pack(vertices[face[0]]),
            ])
            for i in range(4):
                a = vertices[face[i]]
                b = vertices[face[(i + 1) % 4]]
                edges.append(a)
                edges.append(b)

        self.vertex_data = np.array(tris, dtype='f4')
        vbo = self.ctx.buffer(self.vertex_data.tobytes())
        self.vao = self.ctx.vertex_array(
            self.prog,
            [(vbo, '3f 1f', 'in_position', 'in_face_kind')],
        )

        # Wireframe program and geometry
        self.line_prog = self.ctx.program(
            vertex_shader="""
            #version 330
            in vec3 in_position;
            uniform mat4 model;
            uniform mat4 projection;
            uniform float line_bias;
            void main() {
                vec4 p = projection * model * vec4(in_position, 1.0);
                p.z -= line_bias * p.w;
                gl_Position = p;
            }
            """,
            fragment_shader="#version 330\nout vec4 fragColor; void main() { fragColor = vec4(0.0, 0.0, 0.0, 1.0); }"
        )
        self.line_model = self.line_prog['model']
        self.line_proj = self.line_prog['projection']
        self.line_bias = self.line_prog['line_bias']
        # Push wireframe lines slightly toward the camera to avoid z-fighting
        # with shaded faces, especially when the front-most segment is near the
        # near plane.
        self.line_bias.value = 1e-3
        edge_data = np.array(edges, dtype='f4')
        line_vbo = self.ctx.buffer(edge_data.tobytes())
        self.line_vao = self.ctx.simple_vertex_array(self.line_prog, line_vbo, 'in_position')

        back_vertices = np.array([
            [-w/2, -h/2, 0], [w/2, -h/2, 0], [w/2, h/2, 0],
            [w/2, h/2, 0], [-w/2, h/2, 0], [-w/2, -h/2, 0]
        ], dtype='f4')
        back_vbo = self.ctx.buffer(back_vertices.tobytes())
        self.back_vao = self.ctx.simple_vertex_array(self.back_prog, back_vbo, 'in_position')

    def render_frame(self, cam_z):
        self.depth_mode = self.params.get('depth_markers', 'none')
        aspect = self.width / self.height
        # Field of view is configurable so users can control perceived depth.
        fovy_deg = self.params.get('fovy', 45.0)
        fovy = np.radians(fovy_deg)
        f = 1.0 / np.tan(fovy / 2)
        near = max(0.05, FRONT_OFFSET * 0.4)
        far = max(self.layout.back_plane_depth + 10.0, self.layout.max_visible_distance + 10.0)
        proj = np.array([
            [f/aspect,0,0,0],
            [0,f,0,0],
            [0,0,(far+near)/(near-far),2*far*near/(near-far)],
            [0,0,-1,0]
        ], dtype='f4')
        self.projection.write(proj.T.tobytes())
        self.back_proj.write(proj.T.tobytes())

        fbo = self.fbo
        fbo.use()
        #fbo.clear(1, 1, 1, 1)
        c = self.params['back_plane_color']
        fbo.clear(c, c, c, 1.0, depth=1.0)


        model = np.eye(4, dtype='f4')
        model[2, 3] = cam_z - self.layout.back_plane_depth
        self.back_model.write(model.T.tobytes())
        self.back_brightness.value = self.params['back_plane_color']
        self.back_color_mode.value = self.params['color_mode'] == 'color'
        self.back_base_color.value = self.params['color_rgb']
        self.back_vao.render()

        self.layout.params = self.params
        segments_to_draw = self.layout.visible_segments(cam_z)
        fade_back_enabled = self.params.get('fade_to_back', False)
        self.fade_back.value = fade_back_enabled
        self.fade_start.value = self.params.get('fade_to_back_start', 10.0)
        self.fade_end.value = self.params.get('fade_to_back_end', 400.0)
        self.tunnel_depth.value = max(float(self.layout.back_plane_depth), 1e-6)

        for rel_z, brightness in segments_to_draw:
            self.seg_z.value = rel_z

            model = np.eye(4, dtype='f4')
            model[2, 3] = rel_z
            self.mvp.write(model.T.tobytes())
            self.brightness.value = brightness
            self.shaded.value = self.depth_mode in ['shaded', 'both']
            self.color_mode.value = self.params['color_mode'] == 'color'
            self.base_color.value = self.params['color_rgb']
            self.vao.render()

            if self.depth_mode in ['wireframe', 'both']:
                self.line_model.write(model.T.tobytes())
                self.line_proj.write(proj.T.tobytes())
                self.line_bias.value = 1e-5
                self.line_vao.render(mode=moderngl.LINES)

        self.ctx.finish()
        fbo.read_into(self.frame, components=3)
        # Flip vertically and convert to BGR
        frame = cv2.cvtColor(self.frame[::-1], cv2.COLOR_RGB2BGR)
        if self.render_scale != 1.0:
            frame = cv2.resize(frame, (self.width, self.height), interpolation=cv2.INTER_AREA)
        return frame




    def update_segments_and_geometry(self):
        self.layout.update(self.params)
        self.init_geometry()

    def reinitialize(self, params=None):
        """Rebuild the tunnel with updated parameters."""
        if params:
            validate_params(params)
            self.params = params
        self.width, self.height = self.compute_resolution(self.params)
        self.depth_mode = self.params.get('depth_markers', 'none')
        self.render_scale = self.params.get('render_scale', 1.0)
        self.rwidth = int(self.width * self.render_scale)
        self.rheight = int(self.height * self.render_scale)
        self.fbo.release()
        self.color_rb.release()
        self.depth_rb.release()
        self.color_rb = self.ctx.renderbuffer((self.rwidth, self.rheight))
        self.depth_rb = self.ctx.depth_renderbuffer((self.rwidth, self.rheight))
        self.fbo = self.ctx.framebuffer(
            color_attachments=[self.color_rb],
            depth_attachment=self.depth_rb,
        )
        self.frame = np.empty((self.rheight, self.rwidth, 3), dtype=np.uint8)

        self.update_segments_and_geometry()

    def release(self):
        """Release OpenGL resources."""
        self.fbo.release()
        self.color_rb.release()
        self.depth_rb.release()
        self.ctx.release()


class SoftwareTunnelRenderer:
    """CPU-based renderer that avoids GPU read-backs for ultra-stable previews."""

    def __init__(self, params):
        validate_params(params)
        self.params = params
        self.width, self.height = compute_render_resolution(params)
        self.render_scale = params.get('render_scale', 1.0)
        self.rwidth = int(self.width * self.render_scale)
        self.rheight = int(self.height * self.render_scale)
        self.layout = SegmentLayout(self.params)

    def _project_point(self, x, y, z, f, aspect, near):
        if z >= -near:
            return None
        scale = f / -z
        x_ndc = (x * scale) / aspect
        y_ndc = y * scale
        sx = (x_ndc + 1.0) * 0.5 * self.rwidth
        sy = (1.0 - y_ndc) * 0.5 * self.rheight
        if np.isnan(sx) or np.isnan(sy):
            return None
        return np.array([sx, sy], dtype=np.float32)

    def render_frame(self, cam_z):
        params = self.params
        self.layout.params = params
        segments = self.layout.visible_segments(cam_z)

        background = float(np.clip(params['back_plane_color'], 0.0, 1.0))
        frame = np.full((self.rheight, self.rwidth, 3), int(background * 255), dtype=np.uint8)

        aspect = self.rwidth / self.rheight
        fovy = np.radians(params.get('fovy', 45.0))
        f = 1.0 / np.tan(fovy / 2.0)
        near = max(0.05, FRONT_OFFSET * 0.4)

        half_w = params['tunnel_width'] / 2.0
        half_h = params['tunnel_height'] / 2.0
        seg_length = self.layout.seg_length

        local_vertices = np.array([
            [-half_w, -half_h, 0.0],
            [half_w, -half_h, 0.0],
            [half_w, half_h, 0.0],
            [-half_w, half_h, 0.0],
            [-half_w, -half_h, -seg_length],
            [half_w, -half_h, -seg_length],
            [half_w, half_h, -seg_length],
            [-half_w, half_h, -seg_length],
        ], dtype=np.float32)

        faces = {
            'left': [0, 3, 7, 4],
            'right': [1, 2, 6, 5],
            'top': [3, 2, 6, 7],
            'bottom': [0, 1, 5, 4],
        }
        edge_pairs = [
            (0, 1), (1, 2), (2, 3), (3, 0),
            (4, 5), (5, 6), (6, 7), (7, 4),
            (0, 4), (1, 5), (2, 6), (3, 7),
        ]

        draw_mode = params.get('depth_markers', 'none')
        shaded = params.get('shaded', True) and draw_mode in ['shaded', 'both']
        wireframe = draw_mode in ['wireframe', 'both']

        if params['color_mode'] == 'color': 
            base_color = np.array(params.get('color_rgb', (1.0, 1.0, 1.0)))[::-1] * 255.0
        else:
            base_color = np.array([255.0, 255.0, 255.0], dtype=np.float32)

        tunnel_depth = self.layout.back_plane_depth

        fade_back_enabled = params.get('fade_to_back', False)
        fade_start = float(params.get('fade_to_back_start', 10.0))
        fade_end = float(params.get('fade_to_back_end', 400.0))

        def smoothstep(edge0, edge1, x):
            t = np.clip((x - edge0) / (edge1 - edge0), 0.0, 1.0)
            return t * t * (3.0 - 2.0 * t)

        for rel_z, brightness in segments:
            pts = []
            skip_segment = False
            for vx, vy, vz in local_vertices:
                projected = self._project_point(vx, vy, vz + rel_z, f, aspect, near)
                if projected is None:
                    skip_segment = True
                    break
                pts.append(projected)
            if skip_segment:
                continue

            depth_factor = np.clip(1.0 - min(1.0, abs(rel_z) / tunnel_depth), 0.0, 1.0)

            if fade_back_enabled:
                depth = -rel_z
                fade = smoothstep(fade_start, fade_end, depth)
                fade_factor = np.clip(1.0 - fade, 0.0, 1.0)
            else:
                fade_factor = 1.0

            adjusted_brightness = brightness * fade_factor

            for face_name, indices in faces.items():
                polygon = np.array([pts[i] for i in indices], dtype=np.float32)
                face_shade = 1.0
                if shaded:
                    if face_name == 'top':
                        face_shade = 0.8
                    elif face_name == 'bottom':
                        face_shade = 1.05
                    else:
                        face_shade = 0.9
                    face_shade = np.clip(0.55 + depth_factor * face_shade * 0.45, 0.3, 1.2)
                color_vec = np.clip(base_color * adjusted_brightness * face_shade, 0.0, 255.0)
                cv2.fillConvexPoly(
                    frame,
                    polygon.astype(np.int32),
                    tuple(int(c) for c in color_vec),
                    lineType=cv2.LINE_AA,
                )

            if wireframe:
                for a, b in edge_pairs:
                    pa = pts[a]
                    pb = pts[b]
                    cv2.line(
                        frame,
                        tuple(pa.astype(int)),
                        tuple(pb.astype(int)),
                        (0, 0, 0),
                        1,
                        lineType=cv2.LINE_AA,
                    )

        if self.render_scale != 1.0:
            frame = cv2.resize(frame, (self.width, self.height), interpolation=cv2.INTER_AREA)

        return frame

    def reinitialize(self, params=None):
        if params:
            validate_params(params)
            self.params = params
        self.width, self.height = compute_render_resolution(self.params)
        self.render_scale = self.params.get('render_scale', 1.0)
        self.rwidth = int(self.width * self.render_scale)
        self.rheight = int(self.height * self.render_scale)
        self.layout.update(self.params)

    def release(self):
        return


def create_renderer(params):
    backend = normalize_renderer_backend(params)
    if backend == 'software':
        return SoftwareTunnelRenderer(params)
    return TunnelRenderer(params)